<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>DemonMonkey</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Nullable>enable</Nullable>
        <AssemblyName>DemonMonkey</AssemblyName>
        <LangVersion>latest</LangVersion>
        <Optimize>False</Optimize>
        <DebugType>embedded</DebugType>
    </PropertyGroup>
    <ItemGroup>
      <Compile Include=".github\Displays.cs" />
    </ItemGroup>
    <ItemGroup>
        <Content Include=".github\workflows\build.yml" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Display\" />
    </ItemGroup>

    <Import Project="..\btd6.targets" />
</Project>
